apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: business-clock-ingress
  labels:
    name: business-clock-ingress
spec:
  rules:
  - host: api.hypertheory.com
    https:
      paths:
      - pathType: Prefix
        path: "/clock"
        backend:
          service:
            name: business-clock-api-service
            port: 
              number: 1337
